name: epic-models
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - libjpeg-turbo=2.0.2
  - cudatoolkit=9.0
  - pip=19.1.1
  - python=3.7.3
  - numpy=1.16.4
  - pytorch=1.1.0
  - torchvision=0.3.0
  - pip:
    # The released version of pretrainedmodels has a bug around DataParallel and
    # pytorch 1.0, see the following links for details:
    # - https://github.com/Cadene/pretrained-models.pytorch/pull/145
    # - https://github.com/Cadene/pretrained-models.pytorch/issues/112
    # - https://github.com/Cadene/pretrained-models.pytorch/issues/120
    # - https://github.com/pytorch/pytorch/issues/8637
    - "git+https://github.com/wpwei/pretrained-models.pytorch.git@vision_bug_fix#egg=pretrainedmodels"
